### ISSUE TITLE
Consider the onreadystatechange hack for IE10

### ISSUE THREAD

**Issue by nevir** [kriskowal/asap#48]
http://sampo.kapsi.fi/setImmediate/testOnReadyStateChange.html via http://codeforhire.com/2013/09/21/setimmediate-and-messagechannel-broken-on-internet-explorer-10/ _appears_ to work (and be properly ordered) for IE10. Doesn't fire on IE11 (but we've got native MutationObservers there)

**Comment by kriskowal** [comment]
I would entertain a pull request for a benchmark and a branch with the proposed change and use the benchmark as a basis for evaluation. At this time, this is too low of a yield problem for me to pursue myself. I do not intend to track this issue further.

Thank you for pointing this out. If someone has more time to try test and measure, again, I am open to considering the change.
