### ISSUE TITLE
Browser field contains invalid route in npm

### ISSUE THREAD

**Issue by kamicane** [kriskowal/asap#57]
In 2.0, the browser field was updated to route `"./test/domain.js": "./test/browser-domain.js"`, and the test folder was added to npmignore, thus generating an invalid route when asap is installed via npm.

This causes issues with module resolvers that use the browser field to route requires. Browserify works, since browserify requires the browser routes to be absolute paths first, and it (probably) does not error out on route not found (you can have a billion invalid routes, he doesn't care). [QuickStart](https://github.com/spotify/quickstart) on the other hand, resolves routes left and right (key & value).

Short explanation: If the browser field specifies `"./folder": "./some-route"` QuickStart tries to do things right and (recursively) resolve the browser field keys, following the [browser field spec](https://gist.github.com/defunctzombie/4339901). It resolves `"./folder"` first, because `"./folder"` could be resolved to `"./folder/index.js"` or `"./folder.js"`, or even be routed itself using another entry in the browser field. So for every `require()` every key of the browser field needs to be resolved to see if the result matches the require resolved result, no matter the initial value of the key. And since the npm published version of asap does not contain the /test/ folder, the browser key for `"./test/domain.js"` is unresolvable, therefore generating an invalid route error.

Simplest solution would be to add back tests to npm. In alternative I suppose it would be relatively easy to implement allowing any number of invalid routes in the module resolver code, though not exactly "correct".

**Comment by domenic** [comment]
QuickStart should not try to follow browser fields that do not appear in program code.

**Comment by kamicane** [comment]
The thing is, it cannot know if the browser key does not appear in the program code, short of making browser keys absolute paths only (which, by the way goes against the proposed spec).

Say you route `"a": "b"`, and you `require("c")` I need to first resolve `"c"` (say it resolves to `"SOME_PATH/c.js"`) and then I need to resolve `"a"` too, to see if it resolves to `"SOME_PATH/c.js"` a;sp, which it totally could, given the package `"a"` since there could be another browser key rule along the line to make that happen.

**Comment by domenic** [comment]
Whatever browserify does, you should do.

**Comment by kamicane** [comment]
Even if the approach is not "correct" though?

Another easier example to show the logic around this:

in package.json
```
"browser": {
  "./folder": "./folder-browser.js"
}
```

your package `./lib/file`
```
`require("../folder")`
```

The "correct" approach is to resolve `"../folder"` first (which, say, resolves to `"./folder/file.js"`) then look at browser, and resolve `"./folder"` to see if it resolves to `"./folder/file.js"` and if a match is found, route it to `"./folder-browser.js"`.

The Browserify approach is to simply not allow the key-part of the browser field to be resolveable, therefore in Browserify, this needs to be the package.json:

```
"browser": {
  "./folder/file.js": "./folder-browser.js"
}
```

**Comment by domenic** [comment]
Compatible is correct. Incompatible is incorrect.

**Comment by kamicane** [comment]
I don't necessarily disagree about compatibility, but we digress. The route is still invalid, and having an invalid route in the project just because Browserify is relaxed about routes is a bit meh. The real issue is not how Browserify calculates routes, the real issue is that Browserify does not care if a route does not exist. I was trying to explain why all routes should be resolvable from a logical point of view.

**Comment by domenic** [comment]
The route is resolvable in development, which is one scenario in which browserify is used. It is not resolvable when used as a dependency, which is another scenario in which browserify is used. The browser field spec chose not to create separate `"browserDev"` and `"browser"` fields, but instead to just be relaxed about how it works.

**Comment by kriskowal** [comment]
Adding tests back to the deployed package is not an option. I am sympathetic to the issue, but it is worth pushing back on incompatible tooling in this case.
