### ISSUE TITLE
npm published version 2.05 is not in git

### ISSUE THREAD

**Issue by cyrilMargaria** [kriskowal/asap#71]
npm package indicates https://github.com/kriskowal/asap.git, with git head e7f3d29eed4967ecfcaddbfc9542e2ee12b76227, but this commit is not present in github, nor is tagged(no 2.0.5 and 2.04) tag.

Seems github is missing some sync.

**Comment by kriskowal** [comment]
I’ve pushed master and tags. Thanks for the tip.
