### ISSUE TITLE
Browser-asap requiring wrong raw file (non-browser version).

### ISSUE THREAD

**Issue by aldensc** [kriskowal/asap#73]
Browser-asap requires "./raw" instead of "./browser-raw".  The rollup shim resolution only select which file to include, but does not update require references.  The browser-asap should require the browser raw file.

**Comment by kriskowal** [comment]
Has rollup not been trained to look at the `"browser": {}` field in package.json? Browserify specifies that it can be either a string or an object of individual file mappings. The package.json in ASAP handles the rewrite. I am open to a PR here to mitigate.

**Comment by aldensc** [comment]
We were using the rollup browser option, and it did select the './browser-asap' file, but it was still loading './raw' for some reason.  We've circumvented this issue by avoiding the use of Crypto in our project.  It very well could have been an issue with a babel or lint plugin config and not necessarily rollup.  Either way, I would think the ./browser-asap could require the ./browser-raw directly and not rely on the 'browser' setting replacement.  Or, maybe just wait to see if anyone else runs into this issue.  I think making the change would be the safer bet.  Thanks for the reply.  Regards,

**Comment by kriskowal** [comment]
You are definitely not the only person to encounter this problem. I was
recently told the same story by a colleague at the office.

**Comment by kriskowal** [comment]
I’ve discovered that the problem is that `rollup-plugin-node-resolver` needs a `browser: true` option in its configuration to bundle the correct modules. This addresses the problem completely.
