### ISSUE TITLE
Does asap have an ECCN?

### ISSUE THREAD

**Issue by otramony** [kriskowal/asap#75]
Hello. Our team would like to use/include your library in our product, and since we export outside of the U.S., we're required to provide ECCN (Export Control Classification Number) information for all 3rd-party libraries that may use/include encryption. We noticed some references to encryption in the credentials functionality, so we thought we should ask. Thanks.

**Comment by kriskowal** [comment]
ASAP does not have an ECCN. The published package contains nothing related to cryptography.

I have encrypted certain credentials in the Travis CI configuration file that allow us to run tests on Saucelabs infrastructure using an Amazon S3 bucket to store results. All of this is related to testing, only used by library developers, and not shipped in the published package.

See `package.json`’s files list for what files are incorporated in the published package.

If export control is a concern for your product, please consult a lawyer whether these facts or an ECCN are necessary and sufficient for your use.

**Comment by otramony** [comment]
This will suffice. Thank you, Kris.
