### ISSUE TITLE
Contributors?

### ISSUE THREAD

**Issue by hrieke** [kriskowal/asap#76]
Do you have a contributors file with the names of everyone?
Only reason why I ask is that your Copyright right statement in the license file implies that there is one.
Thanks.

**Comment by kriskowal** [comment]
The contributor list is manifest from the Git history.

https://github.com/kriskowal/asap/graphs/contributors

I believe this should be sufficient for any of the legal uses of a contributor list, like getting sign-off for a license change, but I am not a lawyer.

Please let us know if that is not sufficient for your purposes.
